"""Add RBAC tables: roles, permissions, user_roles

Revision ID: 0303d45d8dc8
Revises: a3b53ce8049d
Create Date: 2026-10-02 13:44:04.327959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0303d45d8dc8'
down_revision: Union[str, Sequence[str], None] = 'a3b53ce8049d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permissions_code'),
    schema='control'
    )
    op.create_index(op.f('ix_control_permissions_code'), 'permissions', ['code'], unique=False, schema='control')
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['control.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name'),
    schema='control'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['control.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['control.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['control.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role'),
    schema='control'
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False, schema='control')
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False, schema='control')
    op.drop_column('tenants', 'updated_at', schema='control')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='control')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles', schema='control')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles', schema='control')
    op.drop_table('user_roles', schema='control')
    op.drop_table('roles', schema='control')
    op.drop_index(op.f('ix_control_permissions_code'), table_name='permissions', schema='control')
    op.drop_table('permissions', schema='control')
    # ### end Alembic commands ###
