"""add LRM core model

Revision ID: 155c27fa561a
Revises: a26af5082dc5
Create Date: 2026-09-14 07:17:30.837674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155c27fa561a'
down_revision: Union[str, Sequence[str], None] = 'a26af5082dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collective_agents',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('concepts',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_label', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('scheme', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('entity_relation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=False),
    sa.Column('object_entity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expressions',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('expression_form', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('items',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('shelfmark', sa.String(length=300), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('availability_status', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('manifestations',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('publication_statement', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.String(length=100), nullable=True),
    sa.Column('edition_statement', sa.String(length=500), nullable=True),
    sa.Column('carrier_type', sa.String(length=100), nullable=True),
    sa.Column('extent', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('nomens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('script', sa.String(length=100), nullable=True),
    sa.Column('nomen_type', sa.String(length=100), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('given_name', sa.String(length=250), nullable=True),
    sa.Column('family_name', sa.String(length=250), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('places',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('place_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('time_spans',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('begin_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('expression_agent_relation',
    sa.Column('expression_entity_id', sa.Uuid(), nullable=False),
    sa.Column('agent_entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expression_entity_id'], ['expressions.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expression_entity_id', 'agent_entity_id', 'role')
    )
    op.create_table('expression_manifestation',
    sa.Column('expression_entity_id', sa.Uuid(), nullable=False),
    sa.Column('manifestation_entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['expression_entity_id'], ['expressions.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manifestation_entity_id'], ['manifestations.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expression_entity_id', 'manifestation_entity_id')
    )
    op.create_table('item_agent_relation',
    sa.Column('item_entity_id', sa.Uuid(), nullable=False),
    sa.Column('agent_entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_entity_id'], ['items.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_entity_id', 'agent_entity_id', 'role')
    )
    op.create_table('manifestation_agent_relation',
    sa.Column('manifestation_entity_id', sa.Uuid(), nullable=False),
    sa.Column('agent_entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manifestation_entity_id'], ['manifestations.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manifestation_entity_id', 'agent_entity_id', 'role')
    )
    op.create_table('manifestation_item',
    sa.Column('manifestation_entity_id', sa.Uuid(), nullable=False),
    sa.Column('item_entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_entity_id'], ['items.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manifestation_entity_id'], ['manifestations.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manifestation_entity_id', 'item_entity_id')
    )
    op.create_table('work_agent_relation',
    sa.Column('work_entity_id', sa.Uuid(), nullable=False),
    sa.Column('agent_entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_entity_id'], ['works.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_entity_id', 'agent_entity_id', 'role')
    )
    op.create_table('work_expression',
    sa.Column('work_entity_id', sa.Uuid(), nullable=False),
    sa.Column('expression_entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['expression_entity_id'], ['expressions.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_entity_id'], ['works.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_entity_id', 'expression_entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_expression')
    op.drop_table('work_agent_relation')
    op.drop_table('manifestation_item')
    op.drop_table('manifestation_agent_relation')
    op.drop_table('item_agent_relation')
    op.drop_table('expression_manifestation')
    op.drop_table('expression_agent_relation')
    op.drop_table('time_spans')
    op.drop_table('places')
    op.drop_table('persons')
    op.drop_table('nomens')
    op.drop_table('manifestations')
    op.drop_table('items')
    op.drop_table('expressions')
    op.drop_table('entity_relation')
    op.drop_table('concepts')
    op.drop_table('collective_agents')
    # ### end Alembic commands ###
