"""add source classifications

Revision ID: 45ad1409d3f7
Revises: bb124cb7ee91
Create Date: 2026-09-28 06:39:54.375018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ad1409d3f7'
down_revision: Union[str, Sequence[str], None] = 'bb124cb7ee91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_entity_id', sa.Uuid(), nullable=False),
    sa.Column('institution_entity_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_edition_id', sa.Uuid(), nullable=True),
    sa.Column('notation', sa.String(length=300), nullable=False),
    sa.Column('source_record_id', sa.String(length=500), nullable=True),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_entity_id'], ['collective_agents.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_edition_id'], ['vocabulary_scheme_editions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheme_id'], ['vocabulary_schemes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_entity_id'], ['works.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_entity_id', 'institution_entity_id', 'scheme_id', 'notation', 'source_record_id', name='uq_source_classification_observation')
    )
    op.create_index(op.f('ix_source_classifications_institution_entity_id'), 'source_classifications', ['institution_entity_id'], unique=False)
    op.create_index(op.f('ix_source_classifications_scheme_id'), 'source_classifications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_source_classifications_work_entity_id'), 'source_classifications', ['work_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_classifications_work_entity_id'), table_name='source_classifications')
    op.drop_index(op.f('ix_source_classifications_scheme_id'), table_name='source_classifications')
    op.drop_index(op.f('ix_source_classifications_institution_entity_id'), table_name='source_classifications')
    op.drop_table('source_classifications')
    # ### end Alembic commands ###
