"""add relation predicates

Revision ID: 5b63bb64cf15
Revises: f36733cd6915
Create Date: 2026-09-24 07:58:02.021875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b63bb64cf15'
down_revision: Union[str, Sequence[str], None] = 'f36733cd6915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_predicates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_scheme', sa.String(length=200), nullable=True),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('inverse_predicate_id', sa.Uuid(), nullable=True),
    sa.Column('symmetric', sa.Boolean(), nullable=False),
    sa.Column('transitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inverse_predicate_id'], ['relation_predicates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_predicates_code'), 'relation_predicates', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_predicates_code'), table_name='relation_predicates')
    op.drop_table('relation_predicates')
    # ### end Alembic commands ###
