"""add source records

Revision ID: 6db8e3160623
Revises: 79266f7d5bad
Create Date: 2026-09-28 10:29:01.259526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db8e3160623'
down_revision: Union[str, Sequence[str], None] = '79266f7d5bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=500), nullable=False),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('institution_entity_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_entity_id'], ['collective_agents.entity_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_source_record_system_record')
    )
    op.create_index(op.f('ix_source_records_institution_entity_id'), 'source_records', ['institution_entity_id'], unique=False)
    op.create_index('ix_source_records_system_type', 'source_records', ['source_system', 'record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_records_system_type', table_name='source_records')
    op.drop_index(op.f('ix_source_records_institution_entity_id'), table_name='source_records')
    op.drop_table('source_records')
    # ### end Alembic commands ###
