"""add classification mapping model

Revision ID: 73a210191b7b
Revises: 4677ebcd79c0
Create Date: 2026-09-21 13:27:47.890070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a210191b7b'
down_revision: Union[str, Sequence[str], None] = '4677ebcd79c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_classification_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_classification_entity_id', sa.Uuid(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('mapping_method', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('source_scheme_version', sa.String(length=100), nullable=True),
    sa.Column('target_scheme_version', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mapping_type IN ('exact_match', 'close_match', 'broad_match', 'narrow_match', 'related_match')", name='ck_classification_mapping_type'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_classification_mapping_confidence'),
    sa.CheckConstraint('source_classification_entity_id <> target_classification_entity_id', name='ck_classification_mapping_not_self'),
    sa.ForeignKeyConstraint(['source_classification_entity_id'], ['classification_nodes.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_classification_entity_id'], ['classification_nodes.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_classification_entity_id', 'target_classification_entity_id', 'mapping_type', name='uq_classification_mapping')
    )
    op.create_index(op.f('ix_classification_mappings_source_classification_entity_id'), 'classification_mappings', ['source_classification_entity_id'], unique=False)
    op.create_index(op.f('ix_classification_mappings_target_classification_entity_id'), 'classification_mappings', ['target_classification_entity_id'], unique=False)
    op.add_column('classification_nodes', sa.Column('notation_end', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification_nodes', 'notation_end')
    op.drop_index(op.f('ix_classification_mappings_target_classification_entity_id'), table_name='classification_mappings')
    op.drop_index(op.f('ix_classification_mappings_source_classification_entity_id'), table_name='classification_mappings')
    op.drop_table('classification_mappings')
    # ### end Alembic commands ###
