"""Add field_assertions and field_assertion_audits tables for provenance

Revision ID: 7f016f35c95d
Revises: 0303d45d8dc8
Create Date: 2026-10-02 13:45:52.500265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f016f35c95d'
down_revision: Union[str, Sequence[str], None] = '0303d45d8dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_assertion_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assertion_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['field_assertions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['control.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_assertion_audits_assertion', 'field_assertion_audits', ['assertion_id'], unique=False)
    op.create_index('ix_field_assertion_audits_at', 'field_assertion_audits', ['changed_at'], unique=False)
    
    # Drop old authority_candidates table (obsolete)
    op.drop_index(op.f('ix_authority_candidates_incoming_entity'), table_name='authority_candidates')
    op.drop_index(op.f('ix_authority_candidates_open'), table_name='authority_candidates', postgresql_where="(status = 'open'::text)")
    op.drop_index(op.f('uq_authority_candidates_open'), table_name='authority_candidates', postgresql_where="(status = 'open'::text)")
    op.drop_table('authority_candidates')
    
    # Evolve field_assertions: rename 'field' to 'field_name', 'value' to 'value_text',
    # add new columns for the provenance model.
    
    # First set NULL values in 'field' column to a default value (to avoid NOT NULL violation)
    op.execute("UPDATE field_assertions SET field = 'unknown' WHERE field IS NULL")
    
    # Rename 'field' to 'field_name'
    op.alter_column('field_assertions', 'field',
               new_column_name='field_name')
    
    # Update 'value' (JSONB) to 'value_text' (TEXT) by casting
    op.execute("ALTER TABLE field_assertions RENAME COLUMN value TO value_text")
    op.alter_column('field_assertions', 'value_text',
               type_=sa.Text(),
               postgresql_using='value_text::text')
    
    # Add new columns for structured provenance
    op.add_column('field_assertions', sa.Column('value_json', sa.JSON(), nullable=True))
    op.add_column('field_assertions', sa.Column('language', sa.String(length=100), nullable=True))
    op.add_column('field_assertions', sa.Column('observation_notes', sa.Text(), nullable=True))
    op.add_column('field_assertions', sa.Column('superseded_by_id', sa.Uuid(), nullable=True))
    
    # Update 'confidence' type
    op.alter_column('field_assertions', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Double(),
               existing_nullable=True)
    
    # Update 'status' type and default
    op.alter_column('field_assertions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'proposed'::text"))
    
    # Drop and recreate indexes
    op.drop_index(op.f('ix_field_assertions_open'), table_name='field_assertions', postgresql_where="(status = 'proposed'::text)")
    op.drop_index(op.f('ix_field_assertions_entity'), table_name='field_assertions')
    op.drop_index(op.f('ix_field_assertions_source'), table_name='field_assertions')
    
    op.create_index('ix_field_assertions_entity', 'field_assertions', ['entity_id'], unique=False)
    op.create_index('ix_field_assertions_source', 'field_assertions', ['source_system_id'], unique=False)
    op.create_index('ix_field_assertions_status', 'field_assertions', ['status'], unique=False)
    
    # Create new unique constraint (replaces the old one)
    op.create_unique_constraint('uq_field_assertion_unique_per_source', 'field_assertions', 
                               ['entity_id', 'field_name', 'source_system_id', 'value_text'])
    
    # Update foreign keys
    op.drop_constraint(op.f('field_assertions_source_system_id_fkey'), 'field_assertions', type_='foreignkey')
    op.create_foreign_key(None, 'field_assertions', 'field_assertions', ['superseded_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'field_assertions', 'users', ['reviewed_by'], ['id'], referent_schema='control', ondelete='SET NULL')
    op.create_foreign_key(None, 'field_assertions', 'source_systems', ['source_system_id'], ['id'], ondelete='RESTRICT')
    
    # Drop old columns
    op.drop_column('field_assertions', 'review_note')
    op.drop_column('field_assertions', 'entity_type')
    op.drop_column('field_assertions', 'asserted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse the operations (simplified for safety)
    op.add_column('field_assertions', sa.Column('asserted_by', sa.UUID(), nullable=True))
    op.add_column('field_assertions', sa.Column('entity_type', sa.TEXT(), nullable=False, server_default='unknown'))
    op.add_column('field_assertions', sa.Column('review_note', sa.TEXT(), nullable=True))
    
    # Drop new foreign keys
    op.drop_constraint(None, 'field_assertions', type_='foreignkey')
    op.drop_constraint(None, 'field_assertions', type_='foreignkey')
    
    # Drop new columns
    op.drop_column('field_assertions', 'observation_notes')
    op.drop_column('field_assertions', 'language')
    op.drop_column('field_assertions', 'value_json')
    op.drop_column('field_assertions', 'superseded_by_id')
    
    # Rename columns back
    op.alter_column('field_assertions', 'value_text',
               new_column_name='value')
    op.alter_column('field_assertions', 'field_name',
               new_column_name='field')
    
    # Drop new index
    op.drop_index('ix_field_assertions_status', table_name='field_assertions')
    op.drop_index('ix_field_assertions_source', table_name='field_assertions')
    op.drop_index('ix_field_assertions_entity', table_name='field_assertions')
    
    # Drop table
    op.drop_index('ix_field_assertion_audits_at', table_name='field_assertion_audits')
    op.drop_index('ix_field_assertion_audits_assertion', table_name='field_assertion_audits')
    op.drop_table('field_assertion_audits')
