"""add cardinality constraints

Revision ID: 7f298d228e4d
Revises: a7c963d9b172
Create Date: 2026-09-15 08:13:32.215907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f298d228e4d'
down_revision: Union[str, Sequence[str], None] = 'a7c963d9b172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'manifestation_item', ['item_entity_id'])
    op.create_unique_constraint(None, 'work_expression', ['expression_entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_expression', type_='unique')
    op.drop_constraint(None, 'manifestation_item', type_='unique')
    # ### end Alembic commands ###
