"""add reconciliation decisions

Revision ID: 9625ea922bac
Revises: a082f1c1a99a
Create Date: 2026-09-28 10:39:55.095554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9625ea922bac'
down_revision: Union[str, Sequence[str], None] = 'a082f1c1a99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decision_method', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origin IN ('manual', 'automatic')", name='ck_reconciliation_decision_origin'),
    sa.CheckConstraint("status IN ('accepted', 'rejected', 'unresolved', 'new_entity')", name='ck_reconciliation_decision_status'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_reconciliation_decision_confidence'),
    sa.ForeignKeyConstraint(['candidate_id'], ['reconciliation_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', name='uq_reconciliation_decision_source_record')
    )
    op.create_index(op.f('ix_reconciliation_decisions_candidate_id'), 'reconciliation_decisions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_decisions_source_record_id'), 'reconciliation_decisions', ['source_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_decisions_source_record_id'), table_name='reconciliation_decisions')
    op.drop_index(op.f('ix_reconciliation_decisions_candidate_id'), table_name='reconciliation_decisions')
    op.drop_table('reconciliation_decisions')
    # ### end Alembic commands ###
