"""add reconciliation candidates

Revision ID: a082f1c1a99a
Revises: 6db8e3160623
Create Date: 2026-09-28 10:33:15.786127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a082f1c1a99a'
down_revision: Union[str, Sequence[str], None] = '6db8e3160623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_entity_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0.0 AND score <= 1.0', name='ck_reconciliation_candidate_score'),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'candidate_entity_id', name='uq_reconciliation_candidate')
    )
    op.create_index(op.f('ix_reconciliation_candidates_candidate_entity_id'), 'reconciliation_candidates', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_source_record_id'), 'reconciliation_candidates', ['source_record_id'], unique=False)
    op.create_index('ix_reconciliation_candidates_source_score', 'reconciliation_candidates', ['source_record_id', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliation_candidates_source_score', table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_source_record_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_candidate_entity_id'), table_name='reconciliation_candidates')
    op.drop_table('reconciliation_candidates')
    # ### end Alembic commands ###
