"""Add article qualification table for journal volume/issue/pages

Revision ID: a3b53ce8049d
Revises: b6d9f24c7e31
Create Date: 2026-10-02 13:05:27.211702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b53ce8049d'
down_revision: Union[str, Sequence[str], None] = 'b6d9f24c7e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relation_qualifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_relation_id', sa.Uuid(), nullable=False),
    sa.Column('volume', sa.String(length=100), nullable=True),
    sa.Column('issue', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('article_number', sa.String(length=100), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_relation_id'], ['entity_relation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_relation_id', name='uq_entity_relation_qualifier_per_relation')
    )
    op.create_index(op.f('ix_entity_relation_qualifiers_entity_relation_id'), 'entity_relation_qualifiers', ['entity_relation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_relation_qualifiers_entity_relation_id'), table_name='entity_relation_qualifiers')
    op.drop_table('entity_relation_qualifiers')
    # ### end Alembic commands ###
