"""add unique preferred nomen index

Revision ID: a7c963d9b172
Revises: ca304334b606
Create Date: 2026-09-15 07:28:03.244260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c963d9b172'
down_revision: Union[str, Sequence[str], None] = 'ca304334b606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_nomens_entity_preferred_true', 'nomens', ['entity_id'], unique=True, postgresql_where=sa.text('preferred = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_nomens_entity_preferred_true', table_name='nomens', postgresql_where=sa.text('preferred = true'))
    # ### end Alembic commands ###
