"""add entity merges

Revision ID: b33d2019e9b3
Revises: 9625ea922bac
Create Date: 2026-09-28 10:49:48.301912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33d2019e9b3'
down_revision: Union[str, Sequence[str], None] = '9625ea922bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_merges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('merge_method', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origin IN ('manual', 'automatic')", name='ck_entity_merge_origin'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_entity_merge_confidence'),
    sa.CheckConstraint('source_entity_id <> target_entity_id', name='ck_entity_merge_different_entities'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', name='uq_entity_merge_source')
    )
    op.create_index(op.f('ix_entity_merges_source_entity_id'), 'entity_merges', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_merges_target_entity_id'), 'entity_merges', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_merges_target_entity_id'), table_name='entity_merges')
    op.drop_index(op.f('ix_entity_merges_source_entity_id'), table_name='entity_merges')
    op.drop_table('entity_merges')
    # ### end Alembic commands ###
