"""add relation predicate constraints

Revision ID: bb124cb7ee91
Revises: 5b63bb64cf15
Create Date: 2026-09-24 08:32:37.481821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb124cb7ee91'
down_revision: Union[str, Sequence[str], None] = '5b63bb64cf15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_predicate_constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('predicate_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_type', sa.String(length=100), nullable=False),
    sa.Column('object_entity_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['predicate_id'], ['relation_predicates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predicate_id', 'subject_entity_type', 'object_entity_type', name='uq_relation_predicate_constraint')
    )
    op.create_index(op.f('ix_relation_predicate_constraints_predicate_id'), 'relation_predicate_constraints', ['predicate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_predicate_constraints_predicate_id'), table_name='relation_predicate_constraints')
    op.drop_table('relation_predicate_constraints')
    # ### end Alembic commands ###
