"""add unique constraint to entity relations

Revision ID: ca304334b606
Revises: 155c27fa561a
Create Date: 2026-09-15 07:00:37.283351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca304334b606'
down_revision: Union[str, Sequence[str], None] = '155c27fa561a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_entity_relation_subject_predicate_object', 'entity_relation', ['subject_entity_id', 'predicate', 'object_entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_entity_relation_subject_predicate_object', 'entity_relation', type_='unique')
    # ### end Alembic commands ###
