"""add identifiers

Revision ID: ca8d6e5a605a
Revises: 08f81b9d2a23
Create Date: 2026-09-18 14:13:10.934331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8d6e5a605a'
down_revision: Union[str, Sequence[str], None] = '08f81b9d2a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('qualifier', sa.String(length=500), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'scheme', 'value', name='uq_identifier_entity_scheme_value')
    )
    op.create_index(op.f('ix_identifiers_entity_id'), 'identifiers', ['entity_id'], unique=False)
    op.create_index('ix_identifiers_scheme_value', 'identifiers', ['scheme', 'value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identifiers_scheme_value', table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_entity_id'), table_name='identifiers')
    op.drop_table('identifiers')
    # ### end Alembic commands ###
