"""add classification validations

Revision ID: de3f4dacacac
Revises: 45ad1409d3f7
Create Date: 2026-09-28 07:18:38.384908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3f4dacacac'
down_revision: Union[str, Sequence[str], None] = '45ad1409d3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_validations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_classification_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('warning_code', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('suggested_classification_entity_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validation_method', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('valid', 'warning', 'probable_error', 'unresolved')", name='ck_classification_validation_status'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)', name='ck_classification_validation_confidence'),
    sa.ForeignKeyConstraint(['source_classification_id'], ['source_classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_classification_entity_id'], ['classification_nodes.entity_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_classification_id', name='uq_classification_validation_source')
    )
    op.create_index(op.f('ix_classification_validations_source_classification_id'), 'classification_validations', ['source_classification_id'], unique=False)
    op.create_index(op.f('ix_classification_validations_suggested_classification_entity_id'), 'classification_validations', ['suggested_classification_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_validations_suggested_classification_entity_id'), table_name='classification_validations')
    op.drop_index(op.f('ix_classification_validations_source_classification_id'), table_name='classification_validations')
    op.drop_table('classification_validations')
    # ### end Alembic commands ###
