"""add vocabulary scheme editions

Revision ID: f36733cd6915
Revises: 73a210191b7b
Create Date: 2026-09-21 14:04:55.811015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36733cd6915'
down_revision: Union[str, Sequence[str], None] = '73a210191b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_scheme_editions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['vocabulary_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'edition', name='uq_vocabulary_scheme_edition')
    )
    op.create_index(op.f('ix_vocabulary_scheme_editions_scheme_id'), 'vocabulary_scheme_editions', ['scheme_id'], unique=False)
    op.add_column('classification_nodes', sa.Column('scheme_edition_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_classification_nodes_scheme_edition_id'), 'classification_nodes', ['scheme_edition_id'], unique=False)
    op.create_foreign_key(None, 'classification_nodes', 'vocabulary_scheme_editions', ['scheme_edition_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classification_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_classification_nodes_scheme_edition_id'), table_name='classification_nodes')
    op.drop_column('classification_nodes', 'scheme_edition_id')
    op.drop_index(op.f('ix_vocabulary_scheme_editions_scheme_id'), table_name='vocabulary_scheme_editions')
    op.drop_table('vocabulary_scheme_editions')
    # ### end Alembic commands ###
